Vagrant.configure(2) do |config|

   config.vm.define "cmd2rdf" do |cmd2rdf|
      #cmd2rdf.vm.box = "file:///Users/akmi/CentOS-7.1.1503-x86_64-netboot.box"
      cmd2rdf.vm.box = "https://github.com/holms/vagrant-centos7-box/releases/download/7.1.1503.001/CentOS-7.1.1503-x86_64-netboot.box"
      cmd2rdf.vm.hostname = "cmd2rdf"
      cmd2rdf.vm.network :private_network, ip: "192.168.11.11"
      config.vm.network "forwarded_port", guest: 8080, host: 8080
      config.vm.network "forwarded_port", guest: 8890, host: 8890
      cmd2rdf.vm.provision "ansible" do |ansible|
        #ansible.verbose = "vvvv"
        ansible.playbook = "provisioning/sites.yml"
        ansible.inventory_path = "provisioning/hosts"
        ansible.extra_vars = {}
        ansible.extra_vars["do_build"] = ENV["DO_BUILD"] if !ENV["DO_BUILD"].nil? 
        ansible.extra_vars["cmd2rdf_source_dir"] = ENV["CMD2RDF_SOURCE_DIR"] if !ENV["CMD2RDF_SOURCE_DIR"].nil?
      end
      cmd2rdf.vm.provider "virtualbox" do |vb|
        vb.gui = false
        vb.memory = 4096
        vb.cpus = 2
        vb.customize ["guestproperty", "set", :id, "--timesync-threshold", "1000"]
        vb.customize ["guestproperty", "set", :id, "--timesync-interval", "1000"]
      end
   end
end
