#!/bin/sh
echo "Executing bulk loader script."
echo "Virtuoso home directory: $1"
echo "port: $2"
echo "username: $3"
echo "password: $4"
echo "rdf directory: $5"
$1/bin/isql $2 $3 $4 exec="log_enable(3,1);ld_dir_all('$5', '*.rdf', 'http://eko.indarto/eko.rdf');"
$1/bin/isql $2 $3 $4 exec="log_enable(3,1);rdf_loader_run();"
$1/bin/isql $2 $3 $4 exec="log_enable(3,1);checkpoint;"
echo "Bulk loader: Finish."
